# Generated by Django 3.1.2 on 2020-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Branch Name')),
                ('total_passed', models.IntegerField(default=0, verbose_name='Alumni Count')),
                ('registered_passed', models.IntegerField(default=0, verbose_name='Registered Alumni')),
                ('total_staff', models.IntegerField(default=0, verbose_name='Staff Count')),
                ('registered_staff', models.IntegerField(default=0, verbose_name='Registered Staff')),
                ('year', models.IntegerField(default=2020, verbose_name='Graduation Year')),
            ],
        ),
    ]
