# Generated by Django 3.1.2 on 2020-11-07 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Branch Name')),
                ('total_passed', models.IntegerField(default=0, verbose_name='Alumni Count')),
                ('registered_passed', models.IntegerField(default=0, verbose_name='Registered Alumni')),
                ('total_staff', models.IntegerField(default=0, verbose_name='Staff Count')),
                ('registered_staff', models.IntegerField(default=0, verbose_name='Registered Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, verbose_name='Graduation Year')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/photos')),
                ('doc', models.FileField(blank=True, null=True, upload_to='alumni/docs')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_profile_pic', models.BooleanField(default=False)),
                ('is_cover_pic', models.BooleanField(default=False)),
                ('is_job_update', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.branch')),
                ('connect', models.ManyToManyField(blank=True, related_name='_staff_connect_+', to='portal.Staff')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='year',
            field=models.ManyToManyField(to='portal.Year', verbose_name='Graduation Year'),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.branch')),
                ('connections', models.ManyToManyField(blank=True, related_name='_alumni_connections_+', to='portal.Alumni')),
                ('staff_connections', models.ManyToManyField(blank=True, to='portal.Staff')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Alumni', to=settings.AUTH_USER_MODEL)),
                ('year', models.ManyToManyField(to='portal.Year', verbose_name='Graduation Year')),
            ],
        ),
    ]
