# Generated by Django 3.1.2 on 2020-11-02 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/images')),
                ('doc', models.FileField(blank=True, null=True, upload_to='staff/docs')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('year', models.IntegerField(default=2020, null=True, verbose_name='Graduation Year')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/images')),
                ('doc', models.FileField(blank=True, null=True, upload_to='alumni/docs')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Alumni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
