# Generated by Django 3.1.2 on 2020-11-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='greets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='connections',
            field=models.ManyToManyField(blank=True, to='portal.Alumni'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='connect',
            field=models.ManyToManyField(blank=True, to='portal.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
