# Generated by Django 3.1.2 on 2020-11-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201117_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='connect',
            new_name='connections',
        ),
    ]
