# Generated by Django 3.1.2 on 2020-11-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alumni_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, verbose_name='Graduation Year')),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='year',
        ),
        migrations.AddField(
            model_name='branch',
            name='year',
            field=models.ManyToManyField(to='portal.Year', verbose_name='Graduation Year'),
        ),
    ]
