# Generated by Django 3.1.2 on 2020-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201103_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='year',
            field=models.ManyToManyField(null=True, to='portal.Year', verbose_name='Graduation Year'),
        ),
    ]
