# Generated by Django 3.1.2 on 2020-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201117_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='greeted',
            field=models.ManyToManyField(blank=True, to='portal.Updates'),
        ),
        migrations.AddField(
            model_name='staff',
            name='greeted',
            field=models.ManyToManyField(blank=True, to='portal.Updates'),
        ),
    ]
