# Generated by Django 3.1.2 on 2020-12-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_auto_20201120_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.branch')),
                ('connections', models.ManyToManyField(blank=True, related_name='_profile_connections_+', to='portal.Profile')),
                ('greeted', models.ManyToManyField(blank=True, to='portal.Updates')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumni', to=settings.AUTH_USER_MODEL)),
                ('year', models.ManyToManyField(to='portal.Year', verbose_name='Graduation Year')),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='greeted',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
