# Generated by Django 3.1.2 on 2020-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20201217_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
