# Generated by Django 3.1.2 on 2020-12-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20201218_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
