# Generated by Django 3.1.2 on 2020-12-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_updates_is_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
