# Generated by Django 3.1.2 on 2020-11-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201103_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
