# Generated by Django 3.1.2 on 2020-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201217_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_edited',
            field=models.DateField(null=True),
        ),
    ]
